name: qianduoshao2345

on:
  workflow_dispatch:
  schedule:
    - cron: '58 4/6 * * *'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: qianduoshao2345
        env:
          tx207: ${{ secrets.tx207 }}
        run: |
          echo $tx207 | jq -r .xe1 | /bin/bash
          echo $fqtxo8731 | jq -r .hrc10108 | /bin/bash

